// Package config provides configuration management for the media server.
// It supports JSON files, environment variables (.env), and hot-reloading.
package config

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/bcrypt"

	"media-server-pro/internal/logger"
)

const errConfigPathNotFoundFmt = "config path not found: %s"

// Config holds all server configuration
type Config struct {
	Server        ServerConfig        `json:"server"`
	Directories   DirectoriesConfig   `json:"directories"`
	Streaming     StreamingConfig     `json:"streaming"`
	Download      DownloadConfig      `json:"download"`
	Thumbnails    ThumbnailsConfig    `json:"thumbnails"`
	Analytics     AnalyticsConfig     `json:"analytics"`
	Uploads       UploadsConfig       `json:"uploads"`
	Security      SecurityConfig      `json:"security"`
	Admin         AdminConfig         `json:"admin"`
	Auth          AuthConfig          `json:"auth"`
	HLS           HLSConfig           `json:"hls"`
	RemoteMedia   RemoteMediaConfig   `json:"remote_media"`
	Receiver      ReceiverConfig      `json:"receiver"`
	MatureScanner MatureScannerConfig `json:"mature_scanner"`
	Logging       LoggingConfig       `json:"logging"`
	Features      FeaturesConfig      `json:"features"`
	Database      DatabaseConfig      `json:"database"`
	Updater       UpdaterConfig       `json:"updater"`
	AgeGate       AgeGateConfig       `json:"age_gate"`
	UI            UIConfig            `json:"ui"`
}

// UIConfig holds frontend display defaults
type UIConfig struct {
	ItemsPerPage       int `json:"items_per_page"`
	MobileItemsPerPage int `json:"mobile_items_per_page"`
	MobileGridColumns  int `json:"mobile_grid_columns"`
}

// AgeGateConfig holds age verification gate settings.
// When enabled, visitors must confirm they are 18+ before accessing content.
// Verification is cookie-primary; verified IPs are also cached with a TTL so
// users are not re-prompted if they clear cookies within the TTL window.
// Configured CIDR bypass ranges skip the gate entirely (e.g. admin LAN IPs).
type AgeGateConfig struct {
	Enabled      bool          `json:"enabled"`
	BypassIPs    []string      `json:"bypass_ips"`     // CIDRs that skip the gate (e.g. "192.168.0.0/24")
	IPVerifyTTL  time.Duration `json:"ip_verify_ttl"`  // How long a verified IP is trusted (default: 24h)
	CookieName   string        `json:"cookie_name"`    // Cookie name (default: "age_verified")
	CookieMaxAge int           `json:"cookie_max_age"` // Cookie max-age in seconds (default: 31536000)
}

// UpdaterConfig holds settings for the source-based updater.
// When AppDir and DeployKeyPath are set, the server can perform
// git-pull-based updates instead of downloading GitHub release assets.
type UpdaterConfig struct {
	// AppDir is the path to the application's git repository on disk.
	// If empty, the updater falls back to the directory of the running binary.
	AppDir string `json:"app_dir"`

	// DeployKeyPath is the path to the Ed25519 SSH private key used to
	// authenticate git operations against a private GitHub repository via SSH.
	// Generated by install-cloudpanel.sh when MSP_PRIVATE_REPO=true.
	DeployKeyPath string `json:"deploy_key_path"`

	// GitHubToken is a GitHub personal access token (PAT) or fine-grained token.
	// When set it is used to:
	//   - Authenticate GitHub API calls (allows access to private repos / higher rate limits)
	//   - Authenticate HTTPS git fetch/pull from private repositories
	// Use UPDATER_GITHUB_TOKEN in .env to avoid storing the token in config.json.
	GitHubToken string `json:"github_token"`

	// GitHubUsername is the GitHub account name paired with GitHubToken for HTTPS auth.
	// When set alongside GitHubToken, git and go mod operations authenticate via
	// https://username:token@github.com/ instead of the Authorization header approach,
	// which is more broadly compatible with older git versions and private Go modules.
	// Use UPDATER_GITHUB_USERNAME in .env.
	GitHubUsername string `json:"github_username"`

	// Branch is the git branch to track (default: "main").
	Branch string `json:"branch"`

	// UpdateMethod controls how the admin panel applies updates:
	//   "source"  — git pull + npm build + go build (default)
	//   "binary"  — download pre-built binary from GitHub Releases
	// Use UPDATER_METHOD in .env.
	UpdateMethod string `json:"update_method"`
}

// ServerConfig holds server-specific settings
type ServerConfig struct {
	Host            string        `json:"host"`
	Port            int           `json:"port"`
	ReadTimeout     time.Duration `json:"read_timeout"`
	WriteTimeout    time.Duration `json:"write_timeout"`
	IdleTimeout     time.Duration `json:"idle_timeout"`
	MaxHeaderBytes  int           `json:"max_header_bytes"`
	ShutdownTimeout time.Duration `json:"shutdown_timeout"`
	EnableHTTPS     bool          `json:"enable_https"`
	CertFile        string        `json:"cert_file"`
	KeyFile         string        `json:"key_file"`
}

// DirectoriesConfig holds directory paths
type DirectoriesConfig struct {
	Videos     string `json:"videos"`
	Music      string `json:"music"`
	Thumbnails string `json:"thumbnails"`
	Playlists  string `json:"playlists"`
	Uploads    string `json:"uploads"`
	Analytics  string `json:"analytics"`
	HLSCache   string `json:"hls_cache"`
	Data       string `json:"data"`
	Logs       string `json:"logs"`
	Temp       string `json:"temp"`
}

// StreamingConfig holds streaming settings
type StreamingConfig struct {
	DefaultChunkSize   int64         `json:"default_chunk_size"`
	MaxChunkSize       int64         `json:"max_chunk_size"`
	BufferSize         int           `json:"buffer_size"`
	KeepAliveEnabled   bool          `json:"keep_alive_enabled"`
	KeepAliveTimeout   time.Duration `json:"keep_alive_timeout"`
	Adaptive           bool          `json:"adaptive"`
	MobileOptimization bool          `json:"mobile_optimization"`
	MobileChunkSize    int64         `json:"mobile_chunk_size"`
}

// DownloadConfig holds file download settings
type DownloadConfig struct {
	Enabled     bool `json:"enabled"`
	ChunkSizeKB int  `json:"chunk_size_kb"`
	RequireAuth bool `json:"require_auth"`
}

// ThumbnailsConfig holds thumbnail generation settings
type ThumbnailsConfig struct {
	Enabled          bool `json:"enabled"`
	AutoGenerate     bool `json:"auto_generate"`
	Width            int  `json:"width"`
	Height           int  `json:"height"`
	Quality          int  `json:"quality"`
	VideoInterval    int  `json:"video_interval"`
	PreviewCount     int  `json:"preview_count"`
	GenerateOnAccess bool `json:"generate_on_access"`
	QueueSize        int  `json:"queue_size"`   // Job queue buffer size (default: 1000)
	WorkerCount      int  `json:"worker_count"` // Number of parallel workers (default: 4)
}

// AnalyticsConfig holds analytics settings
type AnalyticsConfig struct {
	Enabled         bool          `json:"enabled"`
	RetentionDays   int           `json:"retention_days"`
	SessionTimeout  time.Duration `json:"session_timeout"`
	CleanupInterval time.Duration `json:"cleanup_interval"`
	TrackPlayback   bool          `json:"track_playback"`
	TrackViews      bool          `json:"track_views"`
}

// UploadsConfig holds upload settings
type UploadsConfig struct {
	Enabled           bool     `json:"enabled"`
	MaxFileSize       int64    `json:"max_file_size"`
	AllowedExtensions []string `json:"allowed_extensions"`
	RequireAuth       bool     `json:"require_auth"`
	ScanForMature     bool     `json:"scan_for_mature"`
}

// SecurityConfig holds security settings
type SecurityConfig struct {
	EnableIPWhitelist bool          `json:"enable_ip_whitelist"`
	IPWhitelist       []string      `json:"ip_whitelist"`
	EnableIPBlacklist bool          `json:"enable_ip_blacklist"`
	IPBlacklist       []string      `json:"ip_blacklist"`
	RateLimitEnabled  bool          `json:"rate_limit_enabled"`
	RateLimitRequests int           `json:"rate_limit_requests"`
	RateLimitWindow   time.Duration `json:"rate_limit_window"`
	BurstLimit        int           `json:"burst_limit"`
	BurstWindow       time.Duration `json:"burst_window"`
	ViolationsForBan  int           `json:"violations_for_ban"`
	BanDuration       time.Duration `json:"ban_duration"`
	MaxFileSizeMB     int           `json:"max_file_size_mb"`
	CSPEnabled        bool          `json:"csp_enabled"`
	CSPPolicy         string        `json:"csp_policy"`
	HSTSEnabled       bool          `json:"hsts_enabled"`
	HSTSMaxAge        int           `json:"hsts_max_age"`
	CORSEnabled       bool          `json:"cors_enabled"`
	CORSOrigins       []string      `json:"cors_origins"`
}

// AdminConfig holds admin panel settings
type AdminConfig struct {
	Enabled        bool          `json:"enabled"`
	Username       string        `json:"username"`
	PasswordHash   string        `json:"password_hash"`
	SessionTimeout time.Duration `json:"session_timeout"`
	QueryTimeout   time.Duration `json:"query_timeout"`
	MaxQueryRows   int           `json:"max_query_rows"`
}

// AuthConfig holds user authentication settings
type AuthConfig struct {
	Enabled          bool          `json:"enabled"`
	SessionTimeout   time.Duration `json:"session_timeout"`
	SecureCookies    bool          `json:"secure_cookies"`
	MaxLoginAttempts int           `json:"max_login_attempts"`
	LockoutDuration  time.Duration `json:"lockout_duration"`
	AllowGuests      bool          `json:"allow_guests"`
	DefaultUserType  string        `json:"default_user_type"`
	UserTypes        []UserType    `json:"user_types"`
}

// UserType defines permissions and limits for a user type
type UserType struct {
	Name                 string `json:"name"`
	StorageQuota         int64  `json:"storage_quota"`
	MaxConcurrentStreams int    `json:"max_concurrent_streams"`
	AllowDownloads       bool   `json:"allow_downloads"`
	AllowUploads         bool   `json:"allow_uploads"`
	AllowPlaylists       bool   `json:"allow_playlists"`
}

// HLSConfig holds HLS streaming settings
type HLSConfig struct {
	Enabled          bool          `json:"enabled"`
	SegmentDuration  int           `json:"segment_duration"`
	PlaylistLength   int           `json:"playlist_length"`
	CleanupEnabled   bool          `json:"cleanup_enabled"`
	CleanupInterval  time.Duration `json:"cleanup_interval"`
	RetentionMinutes int           `json:"retention_minutes"`
	AutoGenerate     bool          `json:"auto_generate"`
	QualityProfiles  []HLSQuality  `json:"quality_profiles"`
	ConcurrentLimit  int           `json:"concurrent_limit"`
}

// HLSQuality defines an HLS quality profile
type HLSQuality struct {
	Name         string `json:"name"`
	Width        int    `json:"width"`
	Height       int    `json:"height"`
	Bitrate      int    `json:"bitrate"`
	AudioBitrate int    `json:"audio_bitrate"`
}

// RemoteMediaConfig holds remote media source settings
type RemoteMediaConfig struct {
	Enabled      bool           `json:"enabled"`
	Sources      []RemoteSource `json:"sources"`
	SyncInterval time.Duration  `json:"sync_interval"`
	CacheEnabled bool           `json:"cache_enabled"`
	CacheSize    int64          `json:"cache_size"`
	CacheTTL     time.Duration  `json:"cache_ttl"`
}

// RemoteSource defines a remote media source connection.
// Username and Password can be provided via environment variables REMOTE_SOURCE_<NAME>_USERNAME
// and REMOTE_SOURCE_<NAME>_PASSWORD to avoid storing credentials in config.json.
type RemoteSource struct {
	Name     string `json:"name"`
	URL      string `json:"url"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	Enabled  bool   `json:"enabled"`
}

// ReceiverConfig holds media receiver (master) settings.
// When enabled, the server acts as a master that accepts media catalog
// registrations from slave nodes and proxies media streams to users on demand.
// No media files are stored on the master — all content is streamed in real-time
// from the originating slave node.
type ReceiverConfig struct {
	Enabled       bool          `json:"enabled"`
	APIKeys       []string      `json:"api_keys"`
	ProxyTimeout  time.Duration `json:"proxy_timeout"`
	HealthCheck   time.Duration `json:"health_check_interval"`
	MaxProxyConns int           `json:"max_proxy_conns"`
	BufferSize    int           `json:"buffer_size"`
}

// MatureScannerConfig holds content scanning settings
type MatureScannerConfig struct {
	Enabled                   bool     `json:"enabled"`
	AutoFlag                  bool     `json:"auto_flag"`
	HighConfidenceThreshold   float64  `json:"high_confidence_threshold"`
	MediumConfidenceThreshold float64  `json:"medium_confidence_threshold"`
	HighConfidenceKeywords    []string `json:"high_confidence_keywords"`
	MediumConfidenceKeywords  []string `json:"medium_confidence_keywords"`
	RequireReview             bool     `json:"require_review"`
}

// LoggingConfig holds logging settings
type LoggingConfig struct {
	Level        string `json:"level"`
	Format       string `json:"format"` // "text" (default) or "json" for structured JSON output; also controlled by LOG_FORMAT env var
	FileEnabled  bool   `json:"file_enabled"`
	FileRotation bool   `json:"file_rotation"` // Rotate log files when MaxFileSize is exceeded; keeps MaxBackups rotated copies
	MaxFileSize  int64  `json:"max_file_size"`
	MaxBackups   int    `json:"max_backups"`
	ColorEnabled bool   `json:"color_enabled"`
}

// FeaturesConfig holds feature toggle settings.
type FeaturesConfig struct {
	EnableHLS           bool `json:"enable_hls"`
	EnableAnalytics     bool `json:"enable_analytics"`
	EnablePlaylists     bool `json:"enable_playlists"`
	EnableUploads       bool `json:"enable_uploads"`
	EnableThumbnails    bool `json:"enable_thumbnails"`
	EnableMatureScanner bool `json:"enable_mature_scanner"`
	EnableRemoteMedia   bool `json:"enable_remote_media"`
	EnableUserAuth      bool `json:"enable_user_auth"`
	EnableAdminPanel    bool `json:"enable_admin_panel"`
	EnableSuggestions   bool `json:"enable_suggestions"`
	EnableAutoDiscovery bool `json:"enable_auto_discovery"`
	EnableReceiver      bool `json:"enable_receiver"`
}

// DatabaseConfig holds database connection settings
type DatabaseConfig struct {
	Enabled         bool          `json:"enabled"`
	Host            string        `json:"host"`
	Port            int           `json:"port"`
	Name            string        `json:"name"`
	Username        string        `json:"username,omitempty"`
	Password        string        `json:"password,omitempty"`
	MaxOpenConns    int           `json:"max_open_conns"`
	MaxIdleConns    int           `json:"max_idle_conns"`
	ConnMaxLifetime time.Duration `json:"conn_max_lifetime"`
	Timeout         time.Duration `json:"timeout"`
	MaxRetries      int           `json:"max_retries"`
	RetryInterval   time.Duration `json:"retry_interval"`
	// TLSMode controls TLS for the database connection.
	// "" or "false" — no TLS (default, fine for localhost).
	// "skip-verify"  — TLS without certificate verification (use for remote/hosted DBs).
	// "true"         — TLS with system CA certificate verification.
	// Set DATABASE_TLS_MODE=skip-verify in .env for hosted database providers.
	TLSMode string `json:"tls_mode,omitempty"`
}

// Manager manages configuration loading, saving, and watching
type Manager struct {
	mu         sync.RWMutex
	config     *Config
	configPath string
	log        *logger.Logger
	watchers   []func(*Config)
}

// NewManager creates a new configuration manager
func NewManager(configPath string) *Manager {
	return &Manager{
		config:     DefaultConfig(),
		configPath: configPath,
		log:        logger.New("config"),
		watchers:   make([]func(*Config), 0),
	}
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	// Port 8080 is used as default to avoid requiring root/Administrator privileges
	// Users needing port 80 can configure it via config.json or SERVER_PORT env var
	return &Config{
		Server: ServerConfig{
			Host:            "0.0.0.0",
			Port:            8080,
			ReadTimeout:     30 * time.Second,
			WriteTimeout:    60 * time.Second,
			IdleTimeout:     120 * time.Second,
			MaxHeaderBytes:  1 << 20, // 1MB
			ShutdownTimeout: 30 * time.Second,
			EnableHTTPS:     false,
		},
		Directories: DirectoriesConfig{
			Videos:     "./videos",
			Music:      "./music",
			Thumbnails: "./thumbnails",
			Playlists:  "./playlists",
			Uploads:    "./uploads",
			Analytics:  "./analytics",
			HLSCache:   "./hls_cache",
			Data:       "./data",
			Logs:       "./logs",
			Temp:       "./temp",
		},
		Streaming: StreamingConfig{
			DefaultChunkSize:   1024 * 1024,      // 1MB
			MaxChunkSize:       10 * 1024 * 1024, // 10MB
			BufferSize:         32 * 1024,        // 32KB
			KeepAliveEnabled:   true,
			KeepAliveTimeout:   60 * time.Second,
			MobileOptimization: true,
			MobileChunkSize:    512 * 1024, // 512KB
		},
		Download: DownloadConfig{
			Enabled:     true,
			ChunkSizeKB: 512,   // 512KB chunks
			RequireAuth: false, // Allow downloads without auth by default
		},
		Thumbnails: ThumbnailsConfig{
			Enabled:          true,
			AutoGenerate:     true,
			Width:            320,
			Height:           180,
			Quality:          80,
			VideoInterval:    30,
			PreviewCount:     10,
			GenerateOnAccess: true,
			QueueSize:        1000, // Large enough for multiple videos with preview thumbnails
			WorkerCount:      4,    // Balance between performance and resource usage
		},
		Analytics: AnalyticsConfig{
			Enabled:         true,
			RetentionDays:   30,
			SessionTimeout:  30 * time.Minute,
			CleanupInterval: 12 * time.Hour,
			TrackPlayback:   true,
			TrackViews:      true,
		},
		Uploads: UploadsConfig{
			Enabled:     true,
			MaxFileSize: 5 * 1024 * 1024 * 1024, // 5GB
			AllowedExtensions: []string{
				".mp4", ".mkv", ".avi", ".mov", ".wmv", ".flv", ".webm",
				".mp3", ".wav", ".flac", ".aac", ".ogg", ".m4a",
			},
			RequireAuth: true,
		},
		Security: SecurityConfig{
			EnableIPWhitelist: false,
			EnableIPBlacklist: false,
			RateLimitEnabled:  true,
			RateLimitRequests: 300,
			RateLimitWindow:   time.Minute,
			BurstLimit:        60,
			BurstWindow:       5 * time.Second,
			ViolationsForBan:  10,
			BanDuration:       15 * time.Minute,
			MaxFileSizeMB:     0, // 0 = no limit
			CSPEnabled:        true,
			CSPPolicy:         "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; font-src 'self' https://cdn.jsdelivr.net; img-src 'self' data: blob:; media-src 'self' blob:; worker-src 'self' blob:; connect-src 'self' blob:",
			HSTSEnabled:       false,
			HSTSMaxAge:        31536000,
			CORSEnabled:       false,
			CORSOrigins:       []string{},
		},
		Admin: AdminConfig{
			Enabled:        true,
			Username:       "admin",
			SessionTimeout: 24 * time.Hour,
			QueryTimeout:   30 * time.Second,
			MaxQueryRows:   1000,
		},
		Auth: AuthConfig{
			Enabled:          true,
			SessionTimeout:   7 * 24 * time.Hour,
			SecureCookies:    false,
			MaxLoginAttempts: 5,
			LockoutDuration:  15 * time.Minute,
			AllowGuests:      true,
			DefaultUserType:  "standard",
			UserTypes: []UserType{
				{Name: "premium", StorageQuota: 100 * 1024 * 1024 * 1024, MaxConcurrentStreams: 5, AllowDownloads: true, AllowUploads: true, AllowPlaylists: true},
				{Name: "standard", StorageQuota: 10 * 1024 * 1024 * 1024, MaxConcurrentStreams: 2, AllowDownloads: true, AllowUploads: false, AllowPlaylists: true},
				{Name: "basic", StorageQuota: 1 * 1024 * 1024 * 1024, MaxConcurrentStreams: 1, AllowDownloads: false, AllowUploads: false, AllowPlaylists: false},
				{Name: "guest", StorageQuota: 0, MaxConcurrentStreams: 1, AllowDownloads: false, AllowUploads: false, AllowPlaylists: false},
			},
		},
		HLS: HLSConfig{
			Enabled:          true,
			SegmentDuration:  6,
			PlaylistLength:   0,
			CleanupEnabled:   true,
			CleanupInterval:  1 * time.Hour,
			RetentionMinutes: 60,
			AutoGenerate:     false,
			ConcurrentLimit:  2,
			QualityProfiles: []HLSQuality{
				{Name: "1080p", Width: 1920, Height: 1080, Bitrate: 5000000, AudioBitrate: 192000},
				{Name: "720p", Width: 1280, Height: 720, Bitrate: 2500000, AudioBitrate: 128000},
				{Name: "480p", Width: 854, Height: 480, Bitrate: 1000000, AudioBitrate: 128000},
				{Name: "360p", Width: 640, Height: 360, Bitrate: 500000, AudioBitrate: 96000},
			},
		},
		RemoteMedia: RemoteMediaConfig{
			Enabled:      false,
			SyncInterval: 1 * time.Hour,
			CacheEnabled: true,
			CacheSize:    1024 * 1024 * 1024, // 1GB
			CacheTTL:     7 * 24 * time.Hour, // 7 days
		},
		Receiver: ReceiverConfig{
			Enabled:       false,
			ProxyTimeout:  60 * time.Second,
			HealthCheck:   30 * time.Second,
			MaxProxyConns: 50,
			BufferSize:    64 * 1024, // 64KB
		},
		MatureScanner: MatureScannerConfig{
			Enabled:                   true,
			AutoFlag:                  true,
			HighConfidenceThreshold:   0.35, // Lowered from 0.5 for stricter detection
			MediumConfidenceThreshold: 0.15, // Lowered from 0.25 for stricter detection
			HighConfidenceKeywords:    []string{"xxx", "porn", "adult", "nsfw"},
			MediumConfidenceKeywords:  []string{"mature", "explicit", "18+"},
			RequireReview:             true,
		},
		Logging: LoggingConfig{
			Level:        "info",
			Format:       "text",
			FileEnabled:  true,
			FileRotation: true,
			MaxFileSize:  100 * 1024 * 1024, // 100MB
			MaxBackups:   5,
			ColorEnabled: true,
		},
		Features: FeaturesConfig{
			EnableHLS:           true,
			EnableAnalytics:     true,
			EnablePlaylists:     true,
			EnableUploads:       true,
			EnableThumbnails:    true,
			EnableMatureScanner: true,
			EnableRemoteMedia:   false,
			EnableUserAuth:      true,
			EnableAdminPanel:    true,
			EnableSuggestions:   true,
			EnableAutoDiscovery: true,
			EnableReceiver:      false,
		},
		Database: DatabaseConfig{
			Enabled:         true, // MySQL is now required
			Host:            "localhost",
			Port:            3306,
			Name:            "mediaserver",
			Username:        "mediaserver",
			Password:        "",
			MaxOpenConns:    25,
			MaxIdleConns:    10,
			ConnMaxLifetime: 1 * time.Hour,
			Timeout:         10 * time.Second,
			MaxRetries:      3,
			RetryInterval:   2 * time.Second,
		},
		Updater: UpdaterConfig{
			Branch:       "main",
			UpdateMethod: "source",
		},
		AgeGate: AgeGateConfig{
			Enabled:      false,
			IPVerifyTTL:  24 * time.Hour,
			CookieName:   "age_verified",
			CookieMaxAge: 365 * 24 * 60 * 60, // 1 year
		},
		UI: UIConfig{
			ItemsPerPage:       48,
			MobileItemsPerPage: 24,
			MobileGridColumns:  2,
		},
	}
}

// Load loads configuration from file and merges with defaults
// Loading order: defaults -> .env file -> config.json -> environment overrides
func (m *Manager) Load() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.log.Info("Loading configuration...")

	// Start with defaults
	m.config = DefaultConfig()

	// Load .env file if it exists (makes env vars available for later override)
	envPath := m.findEnvFile()
	if envPath != "" {
		m.log.Info("Loading environment from %s", envPath)
		if err := m.loadEnvFile(envPath); err != nil {
			m.log.Warn("Failed to load .env file: %v", err)
		}
	}

	// Check if config file exists
	if _, err := os.Stat(m.configPath); os.IsNotExist(err) {
		m.log.Info("Configuration file not found, creating with current settings")
		// Save will persist the config including values from .env
		return m.save()
	}

	// Read config file
	m.log.Info("Loading configuration from %s", m.configPath)
	data, err := os.ReadFile(m.configPath)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	// Parse JSON (this merges with current config, allowing .env to set defaults)
	if err := json.Unmarshal(data, m.config); err != nil {
		return fmt.Errorf("failed to parse config file: %w", err)
	}

	// Apply environment variable overrides (env vars always win over config.json)
	m.applyEnvOverrides()

	// Resolve all relative paths to absolute paths
	m.resolveAbsolutePaths()

	m.log.Info("Configuration loaded successfully")
	return nil
}

// resolveAbsolutePaths converts all relative directory paths to absolute paths.
// This ensures paths work correctly regardless of the working directory from which
// the server is started.
func (m *Manager) resolveAbsolutePaths() {
	// Helper to resolve a path and log any errors
	resolvePath := func(path string, name string) string {
		if path == "" {
			return path
		}
		// If already absolute, return as-is
		if filepath.IsAbs(path) {
			return path
		}
		// Convert to absolute
		absPath, err := filepath.Abs(path)
		if err != nil {
			m.log.Warn("Failed to resolve absolute path for %s (%s): %v", name, path, err)
			return path // Keep original on error
		}
		m.log.Debug("Resolved %s: %s -> %s", name, path, absPath)
		return absPath
	}

	// Resolve all directory paths
	m.config.Directories.Videos = resolvePath(m.config.Directories.Videos, "videos directory")
	m.config.Directories.Music = resolvePath(m.config.Directories.Music, "music directory")
	m.config.Directories.Thumbnails = resolvePath(m.config.Directories.Thumbnails, "thumbnails directory")
	m.config.Directories.Playlists = resolvePath(m.config.Directories.Playlists, "playlists directory")
	m.config.Directories.Uploads = resolvePath(m.config.Directories.Uploads, "uploads directory")
	m.config.Directories.Analytics = resolvePath(m.config.Directories.Analytics, "analytics directory")
	m.config.Directories.HLSCache = resolvePath(m.config.Directories.HLSCache, "HLS cache directory")
	m.config.Directories.Data = resolvePath(m.config.Directories.Data, "data directory")
	m.config.Directories.Logs = resolvePath(m.config.Directories.Logs, "logs directory")
	m.config.Directories.Temp = resolvePath(m.config.Directories.Temp, "temp directory")

	// Resolve HTTPS certificate paths if configured
	if m.config.Server.CertFile != "" {
		m.config.Server.CertFile = resolvePath(m.config.Server.CertFile, "cert file")
	}
	if m.config.Server.KeyFile != "" {
		m.config.Server.KeyFile = resolvePath(m.config.Server.KeyFile, "key file")
	}
}

// findEnvFile looks for .env file in common locations
func (m *Manager) findEnvFile() string {
	// Check for .env in same directory as config file
	configDir := filepath.Dir(m.configPath)
	envPath := filepath.Join(configDir, ".env")
	if _, err := os.Stat(envPath); err == nil {
		return envPath
	}

	// Check current working directory
	if _, err := os.Stat(".env"); err == nil {
		return ".env"
	}

	// Check executable directory
	if exePath, err := os.Executable(); err == nil {
		exeDir := filepath.Dir(exePath)
		envPath = filepath.Join(exeDir, ".env")
		if _, err := os.Stat(envPath); err == nil {
			return envPath
		}
	}

	return ""
}

// stripEnvQuotes removes surrounding single or double quotes from a value.
// Handles basic escaped quotes within strings.
func stripEnvQuotes(value string) string {
	if len(value) < 2 {
		return value
	}

	// Check for matching outer quotes
	if value[0] == '"' && value[len(value)-1] == '"' {
		// Remove outer quotes
		unquoted := value[1 : len(value)-1]
		// Handle escaped double quotes within the string
		return strings.ReplaceAll(unquoted, `\"`, `"`)
	}

	if value[0] == '\'' && value[len(value)-1] == '\'' {
		// Single quotes don't support escape sequences in shell
		return value[1 : len(value)-1]
	}

	// No quotes to strip
	return value
}

// parseEnvLine parses a single KEY=VALUE line. Returns empty key for invalid lines.
func parseEnvLine(line string) (key, value string) {
	idx := strings.Index(line, "=")
	if idx == -1 {
		return "", ""
	}
	key = strings.TrimSpace(line[:idx])
	value = stripEnvQuotes(strings.TrimSpace(line[idx+1:]))
	return key, value
}

// loadEnvFile loads environment variables from a .env file
func (m *Manager) loadEnvFile(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer func() {
		if err := file.Close(); err != nil {
			m.log.Warn("Failed to close .env file: %v", err)
		}
	}()

	scanner := bufio.NewScanner(file)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		key, value := parseEnvLine(line)
		if key == "" {
			m.log.Debug("Skipping invalid line %d in .env: no '=' found", lineNum)
			continue
		}

		// Only set if not already set in environment (allows system env to override .env file)
		if os.Getenv(key) == "" {
			if err := os.Setenv(key, value); err != nil {
				m.log.Warn("Failed to set environment variable %s from .env: %v", key, err)
				// Continue processing other variables even if one fails
			} else {
				m.log.Debug("Set env from .env: %s", key)
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("error reading .env file: %w", err)
	}
	return nil
}

// Save saves the current configuration to file
func (m *Manager) Save() error {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.save()
}

func (m *Manager) save() error {
	data, err := json.MarshalIndent(m.config, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	// Write to temp file first for atomic write
	tempPath := m.configPath + ".tmp"
	if err := os.WriteFile(tempPath, data, 0600); err != nil {
		return fmt.Errorf("failed to write temp config: %w", err)
	}

	// On Windows, os.Rename fails if destination exists, so remove it first
	if _, err := os.Stat(m.configPath); err == nil {
		if err := os.Remove(m.configPath); err != nil {
			return fmt.Errorf("failed to remove old config: %w", err)
		}
	}

	// Rename for atomic update
	if err := os.Rename(tempPath, m.configPath); err != nil {
		if cleanupErr := os.Remove(tempPath); cleanupErr != nil {
			m.log.Warn("Failed to cleanup temp file: %v", cleanupErr)
		}
		return fmt.Errorf("failed to rename config: %w", err)
	}

	m.log.Info("Configuration saved to %s", m.configPath)
	return nil
}

// Get returns a copy of the current configuration, safe for concurrent use.
func (m *Manager) Get() *Config {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.getCopy()
}

// getCopy creates a deep copy of the config without acquiring the lock
// Must be called while holding m.mu (RLock or Lock)
func (m *Manager) getCopy() *Config {
	cp := *m.config
	// Deep copy slices and nested slice fields to prevent shared mutation
	cp.Security.IPWhitelist = append([]string(nil), m.config.Security.IPWhitelist...)
	cp.Security.IPBlacklist = append([]string(nil), m.config.Security.IPBlacklist...)
	cp.Security.CORSOrigins = append([]string(nil), m.config.Security.CORSOrigins...)
	cp.Uploads.AllowedExtensions = append([]string(nil), m.config.Uploads.AllowedExtensions...)
	cp.HLS.QualityProfiles = append([]HLSQuality(nil), m.config.HLS.QualityProfiles...)
	cp.Auth.UserTypes = append([]UserType(nil), m.config.Auth.UserTypes...)
	cp.RemoteMedia.Sources = append([]RemoteSource(nil), m.config.RemoteMedia.Sources...)
	cp.MatureScanner.HighConfidenceKeywords = append([]string(nil), m.config.MatureScanner.HighConfidenceKeywords...)
	cp.MatureScanner.MediumConfidenceKeywords = append([]string(nil), m.config.MatureScanner.MediumConfidenceKeywords...)
	cp.AgeGate.BypassIPs = append([]string(nil), m.config.AgeGate.BypassIPs...)
	return &cp
}

// Update updates the configuration and notifies watchers.
// Watchers receive a deep-copied snapshot of the config taken under lock.
// The update and save are performed atomically under a single lock to ensure
// consistent state and to allow rollback on save failure.
func (m *Manager) Update(updater func(*Config)) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Save original config for rollback in case save fails
	originalJSON, err := json.Marshal(m.config)
	if err != nil {
		return fmt.Errorf("failed to marshal original config for backup: %w", err)
	}

	// Apply updates to in-memory config
	updater(m.config)

	// Persist to disk while holding lock
	if err := m.save(); err != nil {
		// Rollback on save failure
		var rollbackConfig Config
		if unmarshalErr := json.Unmarshal(originalJSON, &rollbackConfig); unmarshalErr == nil {
			m.config = &rollbackConfig
			m.log.Warn("Config save failed, rolled back in-memory changes: %v", err)
		} else {
			m.log.Error("Config save failed AND rollback failed: save error=%v, rollback error=%v", err, unmarshalErr)
		}
		return err
	}

	// Take a snapshot copy for watchers (we hold the lock so getCopy is safe)
	cfg := m.getCopy()

	// Read watchers under lock to avoid racing with OnChange
	watchers := make([]func(*Config), len(m.watchers))
	copy(watchers, m.watchers)

	// Notify watchers with panic recovery
	for _, watcher := range watchers {
		w := watcher
		go func() {
			defer func() {
				if r := recover(); r != nil {
					m.log.Error("Config watcher panic recovered: %v", r)
				}
			}()
			w(cfg)
		}()
	}

	return nil
}

// OnChange registers a callback for configuration changes
func (m *Manager) OnChange(callback func(*Config)) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.watchers = append(m.watchers, callback)
}

// Environment variable helper functions for configuration overrides.

func envGetStr(keys ...string) string {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			return val
		}
	}
	return ""
}

func envGetBool(keys ...string) (bool, bool) {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			return strings.ToLower(val) == "true" || val == "1", true
		}
	}
	return false, false
}

func envGetInt(keys ...string) (int, bool) {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			if i, err := strconv.Atoi(val); err == nil {
				return i, true
			}
		}
	}
	return 0, false
}

func envGetInt64(keys ...string) (int64, bool) {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			if i, err := strconv.ParseInt(val, 10, 64); err == nil {
				return i, true
			}
		}
	}
	return 0, false
}

func envGetFloat64(keys ...string) (float64, bool) {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			if f, err := strconv.ParseFloat(val, 64); err == nil {
				return f, true
			}
		}
	}
	return 0, false
}

func envGetDuration(unit time.Duration, keys ...string) (time.Duration, bool) {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			if i, err := strconv.Atoi(val); err == nil {
				return time.Duration(i) * unit, true
			}
		}
	}
	return 0, false
}

func envGetDurationString(keys ...string) (time.Duration, bool) {
	for _, key := range keys {
		if val := os.Getenv(key); val != "" {
			if d, err := time.ParseDuration(val); err == nil {
				return d, true
			}
		}
	}
	return 0, false
}

// applyEnvOverrides applies environment variable overrides to config.
// Supports both new simplified names (SERVER_PORT) and legacy names (MEDIA_SERVER_PORT).
func (m *Manager) applyEnvOverrides() {
	m.applyServerEnvOverrides()
	m.applyDirectoryEnvOverrides()
	m.applyLoggingEnvOverrides()
	m.applyAuthEnvOverrides()
	m.applyAdminEnvOverrides()
	m.applySecurityEnvOverrides()
	m.applyStreamingEnvOverrides()
	m.applyHLSEnvOverrides()
	m.applyThumbnailsEnvOverrides()
	m.applyAnalyticsEnvOverrides()
	m.applyUploadsEnvOverrides()
	m.applyFeatureEnvOverrides()
	m.applyMatureScannerEnvOverrides()
	m.applyRemoteMediaEnvOverrides()
	m.applyReceiverEnvOverrides()
	m.applyDatabaseEnvOverrides()
	m.applyUpdaterEnvOverrides()
	m.applyAgeGateEnvOverrides()
}

func (m *Manager) applyServerEnvOverrides() {
	if val := envGetStr("SERVER_HOST", "MEDIA_SERVER_HOST"); val != "" {
		m.config.Server.Host = val
		m.log.Debug("Applied env override: Server.Host = %s", val)
	}
	if val, ok := envGetInt("SERVER_PORT", "MEDIA_SERVER_PORT"); ok {
		m.config.Server.Port = val
		m.log.Debug("Applied env override: Server.Port = %d", val)
	}
	if val, ok := envGetBool("SERVER_ENABLE_HTTPS", "MEDIA_SERVER_ENABLE_HTTPS"); ok {
		m.config.Server.EnableHTTPS = val
	}
	if val := envGetStr("SERVER_CERT_FILE"); val != "" {
		m.config.Server.CertFile = val
	}
	if val := envGetStr("SERVER_KEY_FILE"); val != "" {
		m.config.Server.KeyFile = val
	}
	if val, ok := envGetDuration(time.Second, "SERVER_READ_TIMEOUT"); ok {
		m.config.Server.ReadTimeout = val
	}
	if val, ok := envGetDuration(time.Second, "SERVER_WRITE_TIMEOUT"); ok {
		m.config.Server.WriteTimeout = val
	}
	if val, ok := envGetDuration(time.Second, "SERVER_IDLE_TIMEOUT"); ok {
		m.config.Server.IdleTimeout = val
	}
	if val, ok := envGetDuration(time.Second, "SERVER_SHUTDOWN_TIMEOUT"); ok {
		m.config.Server.ShutdownTimeout = val
	}
	if val, ok := envGetInt("SERVER_MAX_HEADER_BYTES"); ok {
		m.config.Server.MaxHeaderBytes = val
	}
}

func (m *Manager) applyDirectoryEnvOverrides() {
	if val := envGetStr("VIDEOS_DIR", "MEDIA_SERVER_VIDEOS_DIR"); val != "" {
		m.config.Directories.Videos = val
	}
	if val := envGetStr("MUSIC_DIR", "MEDIA_SERVER_MUSIC_DIR"); val != "" {
		m.config.Directories.Music = val
	}
	if val := envGetStr("THUMBNAILS_DIR"); val != "" {
		m.config.Directories.Thumbnails = val
	}
	if val := envGetStr("PLAYLISTS_DIR"); val != "" {
		m.config.Directories.Playlists = val
	}
	if val := envGetStr("UPLOADS_DIR"); val != "" {
		m.config.Directories.Uploads = val
	}
	if val := envGetStr("ANALYTICS_DIR"); val != "" {
		m.config.Directories.Analytics = val
	}
	if val := envGetStr("HLS_CACHE_DIR"); val != "" {
		m.config.Directories.HLSCache = val
	}
	if val := envGetStr("DATA_DIR", "MEDIA_SERVER_DATA_DIR"); val != "" {
		m.config.Directories.Data = val
	}
	if val := envGetStr("LOGS_DIR"); val != "" {
		m.config.Directories.Logs = val
	}
	if val := envGetStr("TEMP_DIR"); val != "" {
		m.config.Directories.Temp = val
	}
}

func (m *Manager) applyLoggingEnvOverrides() {
	if val := envGetStr("LOG_LEVEL", "MEDIA_SERVER_LOG_LEVEL"); val != "" {
		m.config.Logging.Level = val
	}
	if val := envGetStr("LOG_FORMAT"); val != "" {
		m.config.Logging.Format = val
	}
	if val, ok := envGetBool("LOG_FILE_ENABLED"); ok {
		m.config.Logging.FileEnabled = val
	}
	if val, ok := envGetBool("LOG_COLOR_ENABLED"); ok {
		m.config.Logging.ColorEnabled = val
	}
	if val, ok := envGetBool("LOG_FILE_ROTATION"); ok {
		m.config.Logging.FileRotation = val
	}
	if val, ok := envGetInt64("LOG_MAX_FILE_SIZE"); ok {
		m.config.Logging.MaxFileSize = val
	}
	if val, ok := envGetInt("LOG_MAX_BACKUPS"); ok {
		m.config.Logging.MaxBackups = val
	}
}

func (m *Manager) applyAuthEnvOverrides() {
	if val, ok := envGetBool("AUTH_ENABLED", "MEDIA_SERVER_ENABLE_AUTH"); ok {
		m.config.Auth.Enabled = val
	}
	if val, ok := envGetBool("AUTH_ALLOW_GUESTS"); ok {
		m.config.Auth.AllowGuests = val
	}
	if val, ok := envGetDuration(time.Hour, "AUTH_SESSION_TIMEOUT_HOURS"); ok {
		m.config.Auth.SessionTimeout = val
	}
	if val, ok := envGetInt("AUTH_MAX_LOGIN_ATTEMPTS"); ok {
		m.config.Auth.MaxLoginAttempts = val
	}
	if val, ok := envGetDuration(time.Minute, "AUTH_LOCKOUT_DURATION_MINUTES"); ok {
		m.config.Auth.LockoutDuration = val
	}
	if val, ok := envGetBool("AUTH_SECURE_COOKIES"); ok {
		m.config.Auth.SecureCookies = val
	}
	if val := envGetStr("AUTH_DEFAULT_USER_TYPE"); val != "" {
		m.config.Auth.DefaultUserType = val
	}
}

func (m *Manager) applyAdminEnvOverrides() {
	if val, ok := envGetBool("ADMIN_ENABLED"); ok {
		m.config.Admin.Enabled = val
	}
	if val := envGetStr("ADMIN_USERNAME", "MEDIA_SERVER_ADMIN_USER"); val != "" {
		m.config.Admin.Username = val
	}
	// Support plaintext ADMIN_PASSWORD by hashing with bcrypt at load time.
	// ADMIN_PASSWORD_HASH takes precedence if both are set.
	if val := envGetStr("ADMIN_PASSWORD_HASH", "MEDIA_SERVER_ADMIN_PASSWORD_HASH"); val != "" {
		m.config.Admin.PasswordHash = val
	} else if val := envGetStr("ADMIN_PASSWORD"); val != "" {
		hash, err := bcrypt.GenerateFromPassword([]byte(val), bcrypt.DefaultCost)
		if err != nil {
			m.log.Error("Failed to hash ADMIN_PASSWORD: %v", err)
		} else {
			m.config.Admin.PasswordHash = string(hash)
			m.log.Info("Admin password set from ADMIN_PASSWORD environment variable")
		}
	}
	if val, ok := envGetDuration(time.Hour, "ADMIN_SESSION_TIMEOUT_HOURS"); ok {
		m.config.Admin.SessionTimeout = val
	}
}

func (m *Manager) applySecurityEnvOverrides() {
	if val, ok := envGetBool("RATE_LIMIT_ENABLED"); ok {
		m.config.Security.RateLimitEnabled = val
	}
	if val, ok := envGetInt("RATE_LIMIT_REQUESTS"); ok {
		m.config.Security.RateLimitRequests = val
	}
	if val, ok := envGetDuration(time.Second, "RATE_LIMIT_WINDOW_SECONDS"); ok {
		m.config.Security.RateLimitWindow = val
	}
	if val, ok := envGetInt("SECURITY_BURST_LIMIT"); ok {
		m.config.Security.BurstLimit = val
	}
	if val, ok := envGetDuration(time.Second, "SECURITY_BURST_WINDOW_SECONDS"); ok {
		m.config.Security.BurstWindow = val
	}
	if val, ok := envGetInt("SECURITY_VIOLATIONS_FOR_BAN"); ok {
		m.config.Security.ViolationsForBan = val
	}
	if val, ok := envGetDuration(time.Minute, "BAN_DURATION_MINUTES"); ok {
		m.config.Security.BanDuration = val
	}
	if val, ok := envGetBool("CORS_ENABLED"); ok {
		m.config.Security.CORSEnabled = val
	}
	if val := envGetStr("CORS_ORIGINS"); val != "" {
		m.config.Security.CORSOrigins = strings.Split(val, ",")
	}
	if val, ok := envGetBool("CSP_ENABLED"); ok {
		m.config.Security.CSPEnabled = val
	}
	if val, ok := envGetBool("HSTS_ENABLED"); ok {
		m.config.Security.HSTSEnabled = val
	}
	if val, ok := envGetInt("HSTS_MAX_AGE"); ok {
		m.config.Security.HSTSMaxAge = val
	}
	if val := envGetStr("CSP_POLICY"); val != "" {
		m.config.Security.CSPPolicy = val
	}
	if val, ok := envGetInt("SECURITY_MAX_FILE_SIZE_MB"); ok {
		m.config.Security.MaxFileSizeMB = val
	}
	if val, ok := envGetBool("SECURITY_ENABLE_IP_WHITELIST"); ok {
		m.config.Security.EnableIPWhitelist = val
	}
	if val := envGetStr("SECURITY_IP_WHITELIST"); val != "" {
		m.config.Security.IPWhitelist = strings.Split(val, ",")
	}
	if val, ok := envGetBool("SECURITY_ENABLE_IP_BLACKLIST"); ok {
		m.config.Security.EnableIPBlacklist = val
	}
	if val := envGetStr("SECURITY_IP_BLACKLIST"); val != "" {
		m.config.Security.IPBlacklist = strings.Split(val, ",")
	}
}

func (m *Manager) applyStreamingEnvOverrides() {
	if val, ok := envGetInt64("STREAMING_CHUNK_SIZE"); ok {
		m.config.Streaming.DefaultChunkSize = val
	}
	if val, ok := envGetInt64("STREAMING_MAX_CHUNK_SIZE"); ok {
		m.config.Streaming.MaxChunkSize = val
	}
	if val, ok := envGetInt("STREAMING_BUFFER_SIZE"); ok {
		m.config.Streaming.BufferSize = val
	}
	if val, ok := envGetBool("STREAMING_KEEP_ALIVE_ENABLED"); ok {
		m.config.Streaming.KeepAliveEnabled = val
	}
	if val, ok := envGetDuration(time.Second, "STREAMING_KEEP_ALIVE_TIMEOUT_SECONDS"); ok {
		m.config.Streaming.KeepAliveTimeout = val
	}
	if val, ok := envGetBool("STREAMING_ADAPTIVE"); ok {
		m.config.Streaming.Adaptive = val
	}
	if val, ok := envGetBool("STREAMING_MOBILE_OPTIMIZATION"); ok {
		m.config.Streaming.MobileOptimization = val
	}
	if val, ok := envGetInt64("STREAMING_MOBILE_CHUNK_SIZE"); ok {
		m.config.Streaming.MobileChunkSize = val
	}
	if val, ok := envGetBool("DOWNLOAD_ENABLED"); ok {
		m.config.Download.Enabled = val
	}
	if val, ok := envGetInt("DOWNLOAD_CHUNK_SIZE_KB"); ok {
		m.config.Download.ChunkSizeKB = val
	}
	if val, ok := envGetBool("DOWNLOAD_REQUIRE_AUTH"); ok {
		m.config.Download.RequireAuth = val
	}
}

func (m *Manager) applyHLSEnvOverrides() {
	if val, ok := envGetBool("HLS_ENABLED"); ok {
		m.config.HLS.Enabled = val
	}
	if val, ok := envGetInt("HLS_SEGMENT_DURATION"); ok {
		m.config.HLS.SegmentDuration = val
	}
	if val, ok := envGetInt("HLS_PLAYLIST_LENGTH"); ok {
		m.config.HLS.PlaylistLength = val
	}
	if val, ok := envGetBool("HLS_CLEANUP_ENABLED"); ok {
		m.config.HLS.CleanupEnabled = val
	}
	if val, ok := envGetDuration(time.Minute, "HLS_CLEANUP_INTERVAL_MINUTES"); ok {
		m.config.HLS.CleanupInterval = val
	}
	if val, ok := envGetInt("HLS_RETENTION_MINUTES"); ok {
		m.config.HLS.RetentionMinutes = val
	}
	if val, ok := envGetBool("HLS_AUTO_GENERATE"); ok {
		m.config.HLS.AutoGenerate = val
	}
	// Accept both HLS_CONCURRENT_LIMIT and the legacy alias HLS_MAX_CONCURRENT_JOBS
	if val, ok := envGetInt("HLS_CONCURRENT_LIMIT", "HLS_MAX_CONCURRENT_JOBS"); ok {
		m.config.HLS.ConcurrentLimit = val
	}
	// HLS_QUALITIES: comma-separated list of quality profile names to enable (e.g. "480p,720p,1080p")
	// Filters the quality profiles loaded from config.json / defaults to only the listed names.
	if raw := envGetStr("HLS_QUALITIES"); raw != "" {
		nameSet := make(map[string]bool)
		for _, name := range strings.Split(raw, ",") {
			nameSet[strings.TrimSpace(name)] = true
		}
		filtered := make([]HLSQuality, 0, len(m.config.HLS.QualityProfiles))
		for _, p := range m.config.HLS.QualityProfiles {
			if nameSet[p.Name] {
				filtered = append(filtered, p)
			}
		}
		if len(filtered) > 0 {
			m.config.HLS.QualityProfiles = filtered
		}
	}
}

func (m *Manager) applyThumbnailsEnvOverrides() {
	if val, ok := envGetBool("THUMBNAILS_ENABLED"); ok {
		m.config.Thumbnails.Enabled = val
	}
	if val, ok := envGetBool("THUMBNAILS_AUTO_GENERATE"); ok {
		m.config.Thumbnails.AutoGenerate = val
	}
	if val, ok := envGetInt("THUMBNAILS_WIDTH"); ok {
		m.config.Thumbnails.Width = val
	}
	if val, ok := envGetInt("THUMBNAILS_HEIGHT"); ok {
		m.config.Thumbnails.Height = val
	}
	if val, ok := envGetInt("THUMBNAILS_QUALITY"); ok {
		m.config.Thumbnails.Quality = val
	}
	if val, ok := envGetInt("THUMBNAILS_VIDEO_INTERVAL"); ok {
		m.config.Thumbnails.VideoInterval = val
	}
	if val, ok := envGetInt("THUMBNAILS_PREVIEW_COUNT"); ok {
		m.config.Thumbnails.PreviewCount = val
	}
	if val, ok := envGetBool("THUMBNAILS_GENERATE_ON_ACCESS"); ok {
		m.config.Thumbnails.GenerateOnAccess = val
	}
	if val, ok := envGetInt("THUMBNAILS_QUEUE_SIZE"); ok {
		m.config.Thumbnails.QueueSize = val
	}
	if val, ok := envGetInt("THUMBNAILS_WORKER_COUNT"); ok {
		m.config.Thumbnails.WorkerCount = val
	}
}

func (m *Manager) applyAnalyticsEnvOverrides() {
	if val, ok := envGetBool("ANALYTICS_ENABLED"); ok {
		m.config.Analytics.Enabled = val
	}
	if val, ok := envGetInt("ANALYTICS_RETENTION_DAYS"); ok {
		m.config.Analytics.RetentionDays = val
	}
	if val, ok := envGetDuration(time.Minute, "ANALYTICS_SESSION_TIMEOUT_MINUTES"); ok {
		m.config.Analytics.SessionTimeout = val
	}
	if val, ok := envGetDuration(time.Minute, "ANALYTICS_CLEANUP_INTERVAL_MINUTES"); ok {
		m.config.Analytics.CleanupInterval = val
	}
	if val, ok := envGetBool("ANALYTICS_TRACK_PLAYBACK"); ok {
		m.config.Analytics.TrackPlayback = val
	}
	if val, ok := envGetBool("ANALYTICS_TRACK_VIEWS"); ok {
		m.config.Analytics.TrackViews = val
	}
}

func (m *Manager) applyUploadsEnvOverrides() {
	if val, ok := envGetBool("UPLOADS_ENABLED"); ok {
		m.config.Uploads.Enabled = val
	}
	if val, ok := envGetInt64("UPLOADS_MAX_FILE_SIZE"); ok {
		m.config.Uploads.MaxFileSize = val
	}
	if val := envGetStr("UPLOADS_ALLOWED_EXTENSIONS"); val != "" {
		m.config.Uploads.AllowedExtensions = strings.Split(val, ",")
	}
	if val, ok := envGetBool("UPLOADS_REQUIRE_AUTH"); ok {
		m.config.Uploads.RequireAuth = val
	}
	if val, ok := envGetBool("UPLOADS_SCAN_FOR_MATURE"); ok {
		m.config.Uploads.ScanForMature = val
	}
}

func (m *Manager) applyFeatureEnvOverrides() {
	// Accept both FEATURE_X (canonical) and FEATURES_X (common in older .env files).
	if val, ok := envGetBool("FEATURE_HLS", "FEATURES_HLS"); ok {
		m.config.Features.EnableHLS = val
	}
	if val, ok := envGetBool("FEATURE_ANALYTICS", "FEATURES_ANALYTICS"); ok {
		m.config.Features.EnableAnalytics = val
	}
	if val, ok := envGetBool("FEATURE_PLAYLISTS", "FEATURES_PLAYLISTS"); ok {
		m.config.Features.EnablePlaylists = val
	}
	if val, ok := envGetBool("FEATURE_UPLOADS", "FEATURES_UPLOADS"); ok {
		m.config.Features.EnableUploads = val
	}
	if val, ok := envGetBool("FEATURE_THUMBNAILS", "FEATURES_THUMBNAILS"); ok {
		m.config.Features.EnableThumbnails = val
	}
	if val, ok := envGetBool("FEATURE_MATURE_SCANNER", "FEATURES_MATURE_SCANNER"); ok {
		m.config.Features.EnableMatureScanner = val
	}
	if val, ok := envGetBool("FEATURE_REMOTE_MEDIA", "FEATURES_REMOTE_MEDIA"); ok {
		m.config.Features.EnableRemoteMedia = val
	}
	if val, ok := envGetBool("FEATURE_USER_AUTH", "FEATURES_USER_AUTH"); ok {
		m.config.Features.EnableUserAuth = val
	}
	if val, ok := envGetBool("FEATURE_ADMIN_PANEL", "FEATURES_ADMIN", "FEATURES_ADMIN_PANEL"); ok {
		m.config.Features.EnableAdminPanel = val
	}
	if val, ok := envGetBool("FEATURE_SUGGESTIONS", "FEATURES_SUGGESTIONS"); ok {
		m.config.Features.EnableSuggestions = val
	}
	if val, ok := envGetBool("FEATURE_AUTO_DISCOVERY", "FEATURES_AUTO_DISCOVERY"); ok {
		m.config.Features.EnableAutoDiscovery = val
	}
	if val, ok := envGetBool("FEATURE_RECEIVER", "FEATURES_RECEIVER"); ok {
		m.config.Features.EnableReceiver = val
	}
}

func (m *Manager) applyMatureScannerEnvOverrides() {
	if val, ok := envGetBool("MATURE_SCANNER_ENABLED"); ok {
		m.config.MatureScanner.Enabled = val
	}
	if val, ok := envGetBool("MATURE_SCANNER_AUTO_FLAG"); ok {
		m.config.MatureScanner.AutoFlag = val
	}
	if val, ok := envGetFloat64("MATURE_SCANNER_HIGH_CONFIDENCE_THRESHOLD"); ok {
		m.config.MatureScanner.HighConfidenceThreshold = val
	}
	if val, ok := envGetFloat64("MATURE_SCANNER_MEDIUM_CONFIDENCE_THRESHOLD"); ok {
		m.config.MatureScanner.MediumConfidenceThreshold = val
	}
	if val := envGetStr("MATURE_SCANNER_HIGH_CONFIDENCE_KEYWORDS"); val != "" {
		m.config.MatureScanner.HighConfidenceKeywords = strings.Split(val, ",")
	}
	if val := envGetStr("MATURE_SCANNER_MEDIUM_CONFIDENCE_KEYWORDS"); val != "" {
		m.config.MatureScanner.MediumConfidenceKeywords = strings.Split(val, ",")
	}
	if val, ok := envGetBool("MATURE_SCANNER_REQUIRE_REVIEW"); ok {
		m.config.MatureScanner.RequireReview = val
	}
}

func (m *Manager) applyRemoteMediaEnvOverrides() {
	if val, ok := envGetBool("REMOTE_MEDIA_ENABLED"); ok {
		m.config.RemoteMedia.Enabled = val
	}
	if val, ok := envGetDuration(time.Minute, "REMOTE_MEDIA_SYNC_INTERVAL_MINUTES"); ok {
		m.config.RemoteMedia.SyncInterval = val
	}
	if val, ok := envGetBool("REMOTE_MEDIA_CACHE_ENABLED"); ok {
		m.config.RemoteMedia.CacheEnabled = val
	}
	if val, ok := envGetInt64("REMOTE_MEDIA_CACHE_SIZE"); ok {
		m.config.RemoteMedia.CacheSize = val
	}
	if val, ok := envGetDuration(time.Hour, "REMOTE_MEDIA_CACHE_TTL_HOURS"); ok {
		m.config.RemoteMedia.CacheTTL = val
	}
}

func (m *Manager) applyReceiverEnvOverrides() {
	if val, ok := envGetBool("RECEIVER_ENABLED"); ok {
		m.config.Receiver.Enabled = val
	}
	if val := envGetStr("RECEIVER_API_KEY", "RECEIVER_API_KEYS"); val != "" {
		m.config.Receiver.APIKeys = []string{val}
	}
	if val, ok := envGetInt("RECEIVER_MAX_PROXY_CONNS"); ok {
		m.config.Receiver.MaxProxyConns = val
	}
	if val, ok := envGetDuration(time.Second, "RECEIVER_PROXY_TIMEOUT_SECONDS"); ok {
		m.config.Receiver.ProxyTimeout = val
	}
	if val, ok := envGetDuration(time.Second, "RECEIVER_HEALTH_CHECK_SECONDS"); ok {
		m.config.Receiver.HealthCheck = val
	}
}

func (m *Manager) applyDatabaseEnvOverrides() {
	if val, ok := envGetBool("DATABASE_ENABLED"); ok {
		m.config.Database.Enabled = val
	}
	if val := envGetStr("DATABASE_HOST"); val != "" {
		m.config.Database.Host = val
	}
	if val, ok := envGetInt("DATABASE_PORT"); ok {
		m.config.Database.Port = val
	}
	if val := envGetStr("DATABASE_NAME"); val != "" {
		m.config.Database.Name = val
	}
	if val := envGetStr("DATABASE_USERNAME"); val != "" {
		m.config.Database.Username = val
	}
	if val := envGetStr("DATABASE_PASSWORD"); val != "" {
		m.config.Database.Password = val
		m.log.Info("Database password set from DATABASE_PASSWORD environment variable")
	}
	if val, ok := envGetInt("DATABASE_MAX_OPEN_CONNS"); ok {
		m.config.Database.MaxOpenConns = val
	}
	if val, ok := envGetInt("DATABASE_MAX_IDLE_CONNS"); ok {
		m.config.Database.MaxIdleConns = val
	}
	if val, ok := envGetDurationString("DATABASE_CONN_MAX_LIFETIME"); ok {
		m.config.Database.ConnMaxLifetime = val
	} else if val, ok := envGetDuration(time.Hour, "DATABASE_CONN_MAX_LIFETIME_HOURS"); ok {
		m.config.Database.ConnMaxLifetime = val
	}
	if val, ok := envGetDurationString("DATABASE_TIMEOUT"); ok {
		m.config.Database.Timeout = val
	} else if val, ok := envGetDuration(time.Second, "DATABASE_TIMEOUT_SECONDS"); ok {
		m.config.Database.Timeout = val
	}
	if val, ok := envGetInt("DATABASE_MAX_RETRIES"); ok {
		m.config.Database.MaxRetries = val
	}
	if val, ok := envGetDurationString("DATABASE_RETRY_INTERVAL"); ok {
		m.config.Database.RetryInterval = val
	} else if val, ok := envGetDuration(time.Second, "DATABASE_RETRY_INTERVAL_SECONDS"); ok {
		m.config.Database.RetryInterval = val
	}
	if val := envGetStr("DATABASE_TLS_MODE"); val != "" {
		m.config.Database.TLSMode = val
	}
}

func (m *Manager) applyUpdaterEnvOverrides() {
	if val := os.Getenv("UPDATER_APP_DIR"); val != "" {
		m.config.Updater.AppDir = val
	}
	if val := os.Getenv("UPDATER_DEPLOY_KEY_PATH"); val != "" {
		m.config.Updater.DeployKeyPath = val
	}
	if val := os.Getenv("UPDATER_GITHUB_TOKEN"); val != "" {
		m.config.Updater.GitHubToken = val
	}
	if val := os.Getenv("UPDATER_GITHUB_USERNAME"); val != "" {
		m.config.Updater.GitHubUsername = val
	}
	if val := os.Getenv("UPDATER_BRANCH"); val != "" {
		m.config.Updater.Branch = val
	}
	if val := os.Getenv("UPDATER_METHOD"); val != "" {
		m.config.Updater.UpdateMethod = val
	}
}

func (m *Manager) applyAgeGateEnvOverrides() {
	if val, ok := envGetBool("AGE_GATE_ENABLED"); ok {
		m.config.AgeGate.Enabled = val
	}
	if val := envGetStr("AGE_GATE_BYPASS_IPS"); val != "" {
		m.config.AgeGate.BypassIPs = strings.Split(val, ",")
	}
	if val, ok := envGetDuration(time.Hour, "AGE_GATE_IP_VERIFY_TTL_HOURS"); ok {
		m.config.AgeGate.IPVerifyTTL = val
	}
	if val := envGetStr("AGE_GATE_COOKIE_NAME"); val != "" {
		m.config.AgeGate.CookieName = val
	}
	if val, ok := envGetInt("AGE_GATE_COOKIE_MAX_AGE"); ok {
		m.config.AgeGate.CookieMaxAge = val
	}
}

// CreateDirectories ensures all configured directories exist
func (m *Manager) CreateDirectories() error {
	m.mu.RLock()
	defer m.mu.RUnlock()

	dirs := []string{
		m.config.Directories.Videos,
		m.config.Directories.Music,
		m.config.Directories.Thumbnails,
		m.config.Directories.Playlists,
		m.config.Directories.Uploads,
		m.config.Directories.Analytics,
		m.config.Directories.HLSCache,
		m.config.Directories.Data,
		m.config.Directories.Logs,
		m.config.Directories.Temp,
	}

	for _, dir := range dirs {
		absDir, err := filepath.Abs(dir)
		if err != nil {
			return fmt.Errorf("failed to resolve path %s: %w", dir, err)
		}

		if err := os.MkdirAll(absDir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", absDir, err)
		}

		// Verify the path is actually a directory
		info, err := os.Stat(absDir)
		if err != nil {
			return fmt.Errorf("failed to stat directory %s: %w", absDir, err)
		}
		if !info.IsDir() {
			return fmt.Errorf("path exists but is not a directory: %s", absDir)
		}

		m.log.Debug("Ensured directory exists: %s", absDir)
	}

	return nil
}

// Validate validates the current configuration
func (m *Manager) Validate() []error {
	m.mu.RLock()
	defer m.mu.RUnlock()

	var errors []error

	// Validate server config
	if m.config.Server.Port < 1 || m.config.Server.Port > 65535 {
		errors = append(errors, fmt.Errorf("invalid server port: %d", m.config.Server.Port))
	}
	// Validate server timeouts to prevent resource exhaustion (log warnings, don't fail)
	if m.config.Server.ReadTimeout <= 0 {
		m.log.Warn("ReadTimeout is %v, timeouts disabled - may cause resource exhaustion", m.config.Server.ReadTimeout)
	}
	if m.config.Server.WriteTimeout <= 0 {
		m.log.Warn("WriteTimeout is %v, timeouts disabled - may cause resource exhaustion", m.config.Server.WriteTimeout)
	}
	if m.config.Server.IdleTimeout <= 0 {
		m.log.Warn("IdleTimeout is %v, timeouts disabled - may cause resource exhaustion", m.config.Server.IdleTimeout)
	}

	// Validate HTTPS config
	if m.config.Server.EnableHTTPS {
		if m.config.Server.CertFile == "" {
			errors = append(errors, fmt.Errorf("HTTPS enabled but no cert_file specified"))
		}
		if m.config.Server.KeyFile == "" {
			errors = append(errors, fmt.Errorf("HTTPS enabled but no key_file specified"))
		}
	}

	// Validate streaming config
	if m.config.Streaming.DefaultChunkSize < 1024 {
		errors = append(errors, fmt.Errorf("chunk_size too small: %d", m.config.Streaming.DefaultChunkSize))
	}

	// Validate admin config (warn only — missing credentials make the account inaccessible but don't prevent startup)
	if m.config.Admin.Enabled && m.config.Admin.Username == "" {
		m.log.Warn("admin enabled but no username specified — admin login will fail until ADMIN_USERNAME is set")
	}
	if m.config.Admin.Enabled && m.config.Admin.PasswordHash == "" {
		m.log.Warn("admin enabled but no password hash — admin login will fail until ADMIN_PASSWORD_HASH is set")
	}

	// Validate rate limiting
	if m.config.Security.RateLimitEnabled && m.config.Security.RateLimitRequests < 1 {
		errors = append(errors, fmt.Errorf("rate_limit_requests must be positive"))
	}

	// Validate HLS segment duration
	if m.config.HLS.Enabled && (m.config.HLS.SegmentDuration < 1 || m.config.HLS.SegmentDuration > 60) {
		errors = append(errors, fmt.Errorf("hls segment_duration must be between 1 and 60 seconds, got: %d", m.config.HLS.SegmentDuration))
	}

	// Database is required — all persistence uses MySQL
	if !m.config.Database.Enabled {
		errors = append(errors, fmt.Errorf("database must be enabled: set DATABASE_ENABLED=true"))
	} else {
		if m.config.Database.Host == "" {
			errors = append(errors, fmt.Errorf("database host is required"))
		}
		if m.config.Database.Port < 1 || m.config.Database.Port > 65535 {
			errors = append(errors, fmt.Errorf("invalid database port: %d", m.config.Database.Port))
		}
		if m.config.Database.Name == "" {
			errors = append(errors, fmt.Errorf("database name is required"))
		}
	}

	// Warn about wildcard CORS with auth enabled
	if m.config.Security.CORSEnabled && m.config.Auth.Enabled {
		for _, origin := range m.config.Security.CORSOrigins {
			if origin == "*" {
				m.log.Warn("SECURITY: Wildcard CORS origin (*) is active with authentication enabled. " +
					"This allows any website to make cross-origin requests with user cookies.")
				break
			}
		}
	}

	return errors
}

// GetValue gets a configuration value by dot-notation path
func (m *Manager) GetValue(path string) (interface{}, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	parts := strings.Split(path, ".")
	v := reflect.ValueOf(m.config).Elem()

	for _, part := range parts {
		if v.Kind() == reflect.Struct {
			v = v.FieldByNameFunc(func(name string) bool {
				return strings.EqualFold(name, part)
			})
			if !v.IsValid() {
				return nil, fmt.Errorf(errConfigPathNotFoundFmt, path)
			}
		} else {
			return nil, fmt.Errorf(errConfigPathNotFoundFmt, path)
		}
	}

	return v.Interface(), nil
}

// normalizeFieldName strips underscores and lowercases for flexible field name matching.
// This allows snake_case paths like "auto_generate" to match CamelCase fields like "AutoGenerate".
func normalizeFieldName(name string) string {
	return strings.ToLower(strings.ReplaceAll(name, "_", ""))
}

// navigateToField traverses the config struct by dot-notation parts and returns the target field.
func navigateToField(root reflect.Value, parts []string, path string) (reflect.Value, error) {
	v := root
	for _, part := range parts {
		if v.Kind() != reflect.Struct {
			return reflect.Value{}, fmt.Errorf(errConfigPathNotFoundFmt, path)
		}
		normalized := normalizeFieldName(part)
		v = v.FieldByNameFunc(func(name string) bool {
			return normalizeFieldName(name) == normalized
		})
		if !v.IsValid() {
			return reflect.Value{}, fmt.Errorf(errConfigPathNotFoundFmt, path)
		}
	}
	return v, nil
}

// setReflectField sets a reflect field value with type conversion.
func setReflectField(field reflect.Value, value interface{}, path string) error {
	if !field.CanSet() {
		return fmt.Errorf("cannot set config value: %s", path)
	}
	newVal := reflect.ValueOf(value)
	if !newVal.Type().ConvertibleTo(field.Type()) {
		return fmt.Errorf("type mismatch for config value: %s", path)
	}
	field.Set(newVal.Convert(field.Type()))
	return nil
}

// SetValue sets a configuration value by dot-notation path
func (m *Manager) SetValue(path string, value interface{}) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	parts := strings.Split(path, ".")
	field, err := navigateToField(reflect.ValueOf(m.config).Elem(), parts, path)
	if err != nil {
		return err
	}
	if err := setReflectField(field, value, path); err != nil {
		return err
	}
	return m.save()
}
